#!/bin/sh

# Search function for DuckDuckGo
# All command-line arguments are passed as search query.

if [ $# == 0 ]; then
    echo "Usage: duck query"
else
    if [ $# != 1 ]; then
	term="$@"
    else
	term=$1
    fi
    open "https://duckduckgo.com/?q=$term&t=osx"
fi
