#!/bin/sh

START=`date +%s`

if [ "$#" -ne 2 ]; then
    echo "Usage: pdftotxt [language-extension] [file]"
    exit 1
fi

lang=$1
y="`pwd`/$2"
echo Will create a OCRed text file for $y

x=`basename "$y"`
name=${x%.*}

mkdir "$name"
cd "$name"

# splitting to individual pages
convert -density 300 $y -type Grayscale -compress lzw -background white +matte -depth 8 out-%05d.tif

# process each page
for f in $( ls *.tif ); do
    # extract text
    tesseract -l $lang $f ${f%.*}
    rm $f
done

# combine all pages back to a single file

cat $(ls) > ../${name}_ocred.txt

cd ..
rm -rf $name

END=`date +%s`
DUR=$(($END-$START))
TIME=`printf "%02d:%02d:%02d" $(($DUR/3600)) $(($DUR/60%60)) $(($DUR%60))`
echo ; echo "### OCR took $TIME ###"