#!/bin/sh

redText='echo -en "\033[31m"'
redOutput='while read line; do redText; echo $line; done'

if mount | grep osxfuse > /dev/null; then
	echo $'Another OSXFUSE volume is already mounted!\nUnmount it first!' | redOutput
else
	if [[ ! -d "/Volumes/Leo Born HD Extension/Data" ]]; then
		mkdir /Volumes/Leo\ Born\ HD\ Extension/Data
	fi
	encfs /Volumes/Leo\ Born\ HD\ Extension/.Data/ /Volumes/Leo\ Born\ HD\ Extension/Data
fi