#!/bin/sh

# Small weather function
# Got the idea from http://osxdaily.com/2016/02/18/get-weather-command-line-finger-graph/ and a comment there
usage() {
	echo "Usage: weather [-option] city"
	echo
    echo "Options (no option defaults to -c):"
    echo "	-c, --current		Output only current weather for the given city."
    echo "	-t, --today		Output only today's weather for the given city."
    echo "	-3, --three-days	Output weather forecast three days (incl. today) for the given city."
}
	
if [ $# == 0 ]; then
	usage
elif [ $# == 1 ]; then
	curl -s http://wttr.in/$1 | head -7
	echo
elif [ $# == 2 ] && ( [[ "$1" == "-c" ]] || [[ "$1" == "--current" ]] ); then
	curl -s http://wttr.in/$2 | head -7
	echo
elif [ $# == 2 ] && ( [[ "$1" == "-t" ]] || [[ "$1" == "--today" ]] ); then
	curl -s http://wttr.in/$2 | head -17
	echo
elif [ $# == 2 ] && ( [[ "$1" == "-3" ]] || [[ "$1" == "--three-days" ]] ); then
	curl -s http://wttr.in/$2 | head -37
	echo
else
	usage
fi